apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: krishnamsg/complete-prodcution-e2e-pipeline:1.0.0-40
      ports:
        - containerPort: 80  # Adjust the container port as needed

