apiVersion: v1
kind: Service
metadata:
  name: test-app-service
spec:
  selector:
    app: test-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080  # Expose the service on port 80
      targetPort: 8080  # Point to the container port
      nodePort: 30081  # Choose a NodePort value (30000-32767) or let Kubernetes assign one

